alc_main: compiler/alc/**/*
ast_lowering: compiler/alc_ast_lowering/**/*
codegen_llvm: compiler/alc_codegen_llvm/**/*
command_option: compiler/alc_command_option/**/*
diagnostic: compiler/alc_diagnostic/**/*
driver: compiler/alc_driver/**/*
parser: compiler/alc_parser/**/*
type_checker: compiler/alc_type_checker/**/*
example: example/**/*
