# Policy: Reduce unnecessary thinking.
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
max_width = 110
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
#use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
