services:
  infra:
    image: hashicorp/terraform:1.3.6
    env_file:
      - infra/credential/docker.admin.env
    volumes:
      - ./infra:/infra
    working_dir: /infra
    entrypoint: ash
    tty: true
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    env_file:
      - infra/credential/docker.admin.env
