name: ci

on: push

env:
  LLVM_VERSION: "13.0.0"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly, stable]
    steps:
      - uses: actions/checkout@v3
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: check
          toolchain: ${{ matrix.toolchain }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check
          toolchain: nightly

  clippy:
#    needs: [check]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: KyleMayes/install-llvm-action@v1
          with:
            version: ${{ env.LLVM_VERSION }}
        - uses: actions-rs/toolchain@v1.0.6
          with:
            profile: minimal
            toolchain: nightly
        - uses: actions-rs/clippy-check@v1.0.7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all-features
